#test file
#panic mode error recovery
for i in rangee(10):
	print("hello")